# Generated by Django 5.0.2 on 2025-06-02 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
